### ISSUE TITLE
spring + spotless - Could not initialize class com.facebook.ktfmt.format.Parser when using kotlinGradle { ktfmt() }

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [diffplug/spotless#2646]
Sample repo that reproduces the issue:
https://github.com/StefanLobbenmeierObjego/spotless-2646

This setup worked in spotless v7:

```build.gradle.kts
import com.diffplug.gradle.spotless.SpotlessExtension
configure<SpotlessExtension> {
    java {
        targetExclude(fileTree("${layout.buildDirectory}/generated") { include("**/*.java") })
        palantirJavaFormat("2.38.0")
    }

    kotlinGradle { ktfmt().kotlinlangStyle() }
}
```

After upgrading to v8 I get this error:

```
> Task :spotlessKotlinGradleApply FAILED
Caching disabled for task ':spotlessKotlinGradleApply' because:
  not worth caching
Task ':spotlessKotlinGradleApply' is not up-to-date because:
  Task has not declared any outputs despite executing actions.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessKotlinGradleApply'.
> There were 2 lint error(s), they must be fixed or suppressed.
  build.gradle.kts:LINE_UNDEFINED ktfmt(java.lang.NoClassDefFoundError) Could not initialize class com.facebook.ktfmt.format.Parser (...)
  settings.gradle.kts:LINE_UNDEFINED ktfmt(java.lang.NoClassDefFoundError) Could not initialize class com.facebook.ktfmt.format.Parser (...)
  Resolve these lints or suppress with `suppressLintsFor`

* Try:
> Run with --debug option to get more log output.
> Run with --scan to generate a Build Scan (Powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spotlessKotlinGradleApply'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:288)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:133)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.api.internal.tasks.execution.ProblemsTaskPathTrackingTaskExecuter.execute(ProblemsTaskPathTrackingTaskExecuter.java:41)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:342)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:338)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:84)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:327)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.GradleException: There were 2 lint error(s), they must be fixed or suppressed.
build.gradle.kts:LINE_UNDEFINED ktfmt(java.lang.NoClassDefFoundError) Could not initialize class com.facebook.ktfmt.format.Parser (...)
settings.gradle.kts:LINE_UNDEFINED ktfmt(java.lang.NoClassDefFoundError) Could not initialize class com.facebook.ktfmt.format.Parser (...)
Resolve these lints or suppress with `suppressLintsFor`
        at com.diffplug.gradle.spotless.SpotlessApply.performAction(SpotlessApply.java:60)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:252)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:237)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:220)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:203)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:170)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:42)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:75)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:46)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:39)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:28)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
        at org.gradle.internal.Either$Right.fold(Either.java:176)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:75)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:53)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:53)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:35)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:64)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:35)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:62)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:40)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:76)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:45)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:136)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:61)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:38)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:297)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:132)
        ... 29 more


BUILD FAILED in 840ms
```

**Comment by nedtwigg** [comment]
- probably caused by something in here https://github.com/diffplug/spotless/pull/2613
- i'm not working on this atm, happy to merge a PR

**Comment by garretcarrot** [comment]
I've been having the same problem since before the recent merges, too! FWIW I tracked down the source of the `ktfmt(java.lang.NoClassDefFoundError)`, and it's due to a runtime exception thrown from the static initializer in ktfmt's Parser class.

In versions of ktfmt 0.54 and earlier, a (now deprecated) field is read that was compatible with Kotlin 2.0.10 and earlier, but starting with ktfmt 0.55 it accesses a field that exists only in Kotlin 2.0.20 and later. In the `spotlessCheck` output from a clean build, I see Gradle downloading Kotlin 1.9.25 JARs, so I assume that's what's being used by default, and that's why, without specifying the Kotlin version, the plugin fails to run.

In the spotless-2646 project, when I set the Kotlin version explicitly in the plugins block, the `NoClassDefFoundError` doesn't happen.

So it's not a bug in Spotless, or even ktfmt really. Looks like we just got unlucky with a breaking change, and I'm not sure there's a workaround, or any way to have Gradle plugins using one version of Kotlin while the rest of a project uses another.

If you are in a position to upgrade your project(s) to Kotlin 2.2+ that would solve the problem. Otherwise I'm planning to just stick with ktfmt 0.54 for now.

**Comment by StefanLobbenmeierObjego** [comment]
brilliant analysis, that fits with my issue as well. The project I reproduced in has no kotlin code, so it also does not have the kotlin dependency set. Without the "kotlin plugin" "spring dependency management plugin" sets the version to 1.9.sth, so then we get this class not found issue.

**Comment by G00fY2** [comment]
For your information, the issue is caused by the spring dependency management plugin. See https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/407

**Comment by NielsDoucet** [comment]
We hit this issue in a large Gradle monorepo that uses Gradle-native BOM imports (`platform(project(":bom"))`) rather than the Spring Dependency Management Plugin.

Environment: Spotless 8.4.0 / Gradle 9.5.0 / Spring Boot BOM 3.5.14 (kotlin-stdlib:1.9.25 declared) / ktfmt 0.61 (default)

After some digging, I believe we identified the underlying mechanism:
                                                             
`GradleProvisioner.forProject(project)` creates configs on the project's own `ConfigurationContainer`. When Spotless provisions ktfmt, it calls `project.getConfigurations().create("spotless${hashCode}")`. This new config is subject to any `configureEach` actions already registered on that project's container (including BOM platforms injected via `platform()` or the Spring DM Plugin). Any project that applies a dependency constraint on kotlin-compiler-embeddable with an unsupported version, will have that version flow into the provisioner config.

`FeatureClassLoader` uses `ClassLoader.getPlatformClassLoader()` as its `URLClassLoader` parent (not the build tool classloader).
The `buildToolClassLoader` (Gradle's own Kotlin version) is only used for `org.slf4j.*` and `com.diffplug.spotless.*`. All other classes, including all of `org.jetbrains.kotlin.*`, must be found in the provisioner's resolved URLs. Gradle's bundled Kotlin is invisible to ktfmt.

`Parser.<clinit>` accesses `CommonConfigurationKeys.MESSAGE_COLLECTOR_KEY`, a field added in kotlin 2.0.20.
Every subsequent use of Parser in that JVM session then gets `NoClassDefFoundError: Could not initialize class com.facebook.ktfmt.format.Parser`. This explains why all formatter invocations fail after the first.
The failure is random because it only manifests when the provisioner config inherits constraints (depends on configureEach registration order during the configuration phase) and no higher-version constraint overrides with a supported kotlin version.

This fully lines up with garretcarrot's analysis above. But I think spotless is in a position to guarantee it works.

### Suggested fix

The provisioner should guarantee a minimum supported Kotlin version when provisioning ktfmt. A targeted guard in `GradleProvisioner.forProject()` would be sufficient:

```java
// In the lambda inside GradleProvisioner.forConfigurationContainer()
Configuration config = configurations.create("spotless"
						+ new Request(withTransitives, mavenCoords).hashCode());
// ... existing setup ...
config.getResolutionStrategy().eachDependency(details -> {
    ModuleVersionSelector requested = details.getRequested();
    if ("org.jetbrains.kotlin".equals(requested.getGroup())) {
        String version = requested.getVersion();
        // ktfmt 0.55+ requires Kotlin 2.0.20+; prevent incompatible kotlin versions
        // from breaking Parser static initialisation via FeatureClassLoader
        // TODO version comparison logic requires some attention, as this simple string comparison is not reliable
        if (version != null && !version.isEmpty() && version.compareTo("2.0.20") < 0) {
            details.useVersion("2.0.20");
            details.because("ktfmt 0.55+ requires Kotlin >= 2.0.20");
        }
    }
});
```            
This should be safe, as it only upgrades, never downgrades and only fires for the ephemeral `spotless{hash}` configurations that the provisioner creates.
