### ISSUE TITLE
Spotless doesn't work with ktlint 0.48.0

### ISSUE THREAD

**Issue by bcmedeiros** [diffplug/spotless#1430]
If you are submitting a **bug**, please include the following:

- [ 6.12.0 ] spotless version

This is stack trace:
```
java.lang.NoSuchMethodError: 'com.pinterest.ktlint.core.api.UsesEditorConfigProperties$EditorConfigProperty com.pinterest.ktlint.core.api.DefaultEditorConfigProperties.getKtlintDisabledRulesProperty()'
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter.createEditorConfigOverride(KtLintCompat0Dot47Dot0Adapter.java:106)
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter.format(KtLintCompat0Dot47Dot0Adapter.java:73)
        at com.diffplug.spotless.glue.ktlint.KtlintFormatterFunc.applyWithFile(KtlintFormatterFunc.java:71)
        at com.diffplug.spotless.FormatterFunc$NeedsFile.apply(FormatterFunc.java:154)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:102)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:88)
```

**Comment by bcmedeiros** [comment]
PR: https://github.com/diffplug/spotless/pull/1432

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 6.12.1` and `plugin-maven 2.29.0` thanks to @davidburstrom with help from @bcmedeiros.

**Comment by eirnym** [comment]
Plugin doesn't work for ktlint `0.47.1` and works for ktlint `0.48.0`

**Comment by davidburstrom** [comment]
Could you please elaborate on how it doesn't work?

**Comment by nedtwigg** [comment]
Thanks for reporting. The version switch is here, this maybe has a bug for `0.47.1` that it doesn't have for `0.47.0`.

https://github.com/diffplug/spotless/blob/86404f1a1708b9fcb97ef8d7c16a43bec9bc7e06/lib/src/ktlint/java/com/diffplug/spotless/glue/ktlint/KtlintFormatterFunc.java#L44-L51

We should probably extend BadSemver to handle the `C` in `A.B.C` and then use that

https://github.com/diffplug/spotless/blob/0fd20bb80c6c426d20e0a3157c3c2b89317032da/lib/src/main/java/com/diffplug/spotless/kotlin/BadSemver.java#L21-L35

example usage

https://github.com/diffplug/spotless/blob/552aabf876469227d4bdc0be0da65b6d746fbc19/lib/src/main/java/com/diffplug/spotless/kotlin/KtfmtStep.java#L177

I'm also tempted for Spotless to just drop support for all versions of KtLint except for the most recent to have a breaking change in its API. The maintenance load for this one formatter is relatively high...

**Comment by eirnym** [comment]
Gradle defines semver wokring as expected only for major version above 0 (breaking changes reflected in major version). When major is 0, minor version reflects breaking changes.

**Comment by bcmedeiros** [comment]
I was trying to upgrade my project and bumped into another issue:
https://github.com/diffplug/spotless/issues/1444
