### ISSUE TITLE
Script compilation error with ktfmt().kotlinlangStyle()

### ISSUE THREAD

**Issue by bjrke** [diffplug/spotless#1917]
when upgrading from 6.22.0 to 6.23.0 of the gradle plugin I get the following error

```
* What went wrong:
Script compilation error:

  Line 125:     spotless { kotlinGradle { ktfmt().kotlinlangStyle() } }
                                                  ^ Cannot access 'BaseKotlinExtension': it is package-private in 'com.diffplug.gradle.spotless'
```

I assume its because of this change https://github.com/diffplug/spotless/commit/a392c72e4383952faa564b892e38357666986cf9
where the visibility of `BaseKotlinExtension` changed

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] Gradle or Maven version
gradle 8.3
- [x] spotless version
6.23.0
- [x] operating system and version
ubuntu 23.0.4
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
see error message
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
can't

If you're just submitting a feature request or question, no need for the above.

**Comment by bjrke** [comment]
just detected #1911 which seems to be the same issue
