### ISSUE TITLE
NoClassDefFoundError's after update to gradle-plugin v8.5.1

### ISSUE THREAD

**Issue by abentele** [diffplug/spotless#2933]
after update from gradle-plugin v8.5.0 to v8.5.1, I get errors for Kotlin files which don't contain any Kotlin classes.

Log output is:
```
...
.../MediaTypes.kt:LINE_UNDEFINED ktlint(java.lang.NoClassDefFoundError) com/pinterest/ktlint/rule/engine/api/EditorConfigDefaults (...)
...
```

The example file MediaTypes.kt has this content:

```
package xyz

const val MEDIA_TYPE_WORD = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
```

**Comment by nunocenteio** [comment]
Isn't the same as #2850?

**Comment by abentele** [comment]
@nunocenteio as the author of this ticket I cannot finally decide this. I already saw this ticket, but as it is related to Spotless Gradle Plugin: 8.2.1, and my ticket is about update from 8.5.0 to 8.5.1, I assume it's a different issue. If not, even better.
